openapi: 3.0.1
info:
  title: Trusted Applications API
  version: v4
externalDocs:
  description: API Documentation
  url: https://portal.nebulaservice.net/docs/developer/en/HTML/trusted-applications.html
servers:
- url: https://api.nebulaservice.net/trustedapps/v1
paths:
  /trusted/app/{id}:
    delete:
      operationId: deleteTrustedApp
      parameters:
      - description: Trusted app identifier
        example: b7530d2a-d035-465b-a549-e81caaba63b6
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Unauthorized
        "403":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Forbidden
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Internal Server Error
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Not Found
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: OK
      security:
      - nebulasuite: []
      summary: Delete a trusted app
      tags:
      - Manage trusted app
      x-accepts:
      - '*/*'
    get:
      operationId: getTrustedApp
      parameters:
      - description: Trusted app identifier
        example: b7530d2a-d035-465b-a549-e81caaba63b6
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Unauthorized
        "403":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Forbidden
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Internal Server Error
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Not Found
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseDetailedTrustedAppViewModel'
          description: OK
      security:
      - nebulasuite: []
      summary: Get a specific trusted app
      tags:
      - Manage trusted app
      x-accepts:
      - '*/*'
    put:
      operationId: updateTrustedApp
      parameters:
      - description: Trusted app identifier
        example: b7530d2a-d035-465b-a549-e81caaba63b6
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTrustedAppViewModel'
        required: true
      responses:
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Unauthorized
        "403":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Forbidden
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Internal Server Error
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Not Found
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseDetailedTrustedAppViewModel'
          description: OK
      security:
      - nebulasuite: []
      summary: Update a trusted app
      tags:
      - Manage trusted app
      x-content-type: application/json
      x-accepts:
      - '*/*'
  /trusted/app/{id}/security:
    put:
      operationId: setSecurityParameters
      parameters:
      - description: Trusted app identifier
        example: b7530d2a-d035-465b-a549-e81caaba63b6
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrustedAppSecParamsViewModel'
        required: true
      responses:
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Unauthorized
        "403":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Forbidden
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Internal Server Error
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Not Found
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: OK
      security:
      - nebulasuite: []
      summary: Modify the security parameters assigned to a trusted app
      tags:
      - Manage trusted app permissions
      x-content-type: application/json
      x-accepts:
      - '*/*'
  /trusted/app/{id}/permissions:
    put:
      operationId: changePermissions
      parameters:
      - description: Trusted app identifier
        example: b7530d2a-d035-465b-a549-e81caaba63b6
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PermissionsBody'
      responses:
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Unauthorized
        "403":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Forbidden
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Internal Server Error
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Not Found
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: OK
      security:
      - nebulasuite: []
      summary: Modify the permissions assigned to a trusted app
      tags:
      - Manage trusted app permissions
      x-content-type: application/json
      x-accepts:
      - '*/*'
  /trusted/app/{id}/groups:
    get:
      description: List only the groups of a trusted app
      operationId: getAllGroups
      parameters:
      - description: Trusted app identifier
        example: b7530d2a-d035-465b-a549-e81caaba63b6
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Unauthorized
        "403":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Forbidden
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Internal Server Error
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Not Found
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseListGroupViewModel'
          description: OK
      security:
      - nebulasuite: []
      summary: Get list of all groups configured in a trusted app
      tags:
      - Manage groups
      x-accepts:
      - '*/*'
    put:
      operationId: changeGroups
      parameters:
      - description: Trusted app identifier
        example: b7530d2a-d035-465b-a549-e81caaba63b6
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessGroupsViewModel'
        required: true
      responses:
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Unauthorized
        "403":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Forbidden
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Internal Server Error
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Not Found
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: OK
      security:
      - nebulasuite: []
      summary: Modify the groups assigned to a trusted app
      tags:
      - Manage groups
      x-content-type: application/json
      x-accepts:
      - '*/*'
  /trusted/app/{id}/accesskey:
    put:
      operationId: regenerateAccessKey
      parameters:
      - description: Trusted app identifier
        example: b7530d2a-d035-465b-a549-e81caaba63b6
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Unauthorized
        "403":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Forbidden
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Internal Server Error
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Not Found
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseRegenerateTrustedAppViewModel'
          description: OK
      security:
      - nebulasuite: []
      summary: Generate signature key for trusted app authorization
      tags:
      - Manage trusted app permissions
      x-accepts:
      - '*/*'
  /trusted/app:
    post:
      operationId: createTrustedApp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTrustedAppViewModel'
        required: true
      responses:
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Unauthorized
        "403":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Forbidden
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Internal Server Error
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Not Found
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseDetailedTrustedAppViewModel'
          description: OK
      security:
      - nebulasuite: []
      summary: Create a new trusted app
      tags:
      - Manage trusted app
      x-content-type: application/json
      x-accepts:
      - '*/*'
  /trusted/app/validate:
    post:
      description: Used to check if the user has the requested permissions from the
        trusted app
      operationId: validatePermission
      parameters:
      - description: Token generated by the authorize endpoint
        example: JWT
        explode: false
        in: header
        name: application
        required: true
        schema:
          type: string
        style: simple
      - description: nebulaSUITE token
        example: Bearer JWT
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - description: Trusted app permission
        example: DISABLE_PIN_POLICY
        explode: true
        in: query
        name: permission
        required: false
        schema:
          description: Permission granted to the trusted app
          enum:
          - DISABLE_AUTH_FIRST
          - DISABLE_AUTH_SECOND
          - DISABLE_PIN_POLICY
          type: string
        style: form
      responses:
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Unauthorized
        "403":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Forbidden
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Internal Server Error
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Not Found
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: OK
      security:
      - nebulasuite: []
      summary: Validate permissions of a user in the trusted app
      tags:
      - Authentication
      x-accepts:
      - '*/*'
  /trusted/app/login/second:
    post:
      description: It is used to obtain a robust nebulaSUITE token from the specified
        user
      operationId: appLoginSecond
      parameters:
      - description: Token generated by the authorize endpoint
        example: JWT
        explode: false
        in: header
        name: application
        required: true
        schema:
          type: string
        style: simple
      - description: Simple nebulaSUITE token
        example: Bearer JWT
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Unauthorized
        "403":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Forbidden
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Internal Server Error
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Not Found
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseLoginResponseViewModel'
          description: OK
      security:
      - nebulasuite: []
      summary: Second factor login
      tags:
      - Authentication
      x-accepts:
      - '*/*'
  /trusted/app/login/first:
    post:
      description: It is used to obtain a simple nebulaSUITE token from the specified
        user
      operationId: appLoginFirst
      parameters:
      - description: Token generated by the authorize endpoint
        example: JWT
        explode: false
        in: header
        name: application
        required: true
        schema:
          type: string
        style: simple
      - description: User UID in base64
        example: b3duZXI=
        explode: true
        in: query
        name: username
        required: true
        schema:
          type: string
        style: form
      responses:
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Unauthorized
        "403":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Forbidden
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Internal Server Error
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Not Found
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseLoginResponseViewModel'
          description: OK
      security:
      - nebulasuite: []
      summary: First factor login
      tags:
      - Authentication
      x-accepts:
      - '*/*'
  /trusted/app/authorize:
    post:
      description: It is used to obtain the token necessary for the trusted app to
        consume the permissions it has
      operationId: authorize
      parameters:
      - description: Token generated by the trusted app
        example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxM2IxODZhNy1jZDVlLTMwNjgtOGIxOS1iYWE1ODBlOTEyMTMiLCJpYXQiOiIxNjY1MTM2NjgyIiwianRpIjoiVVVJRCIsImlzcyI6Iklzc3VlciBhcHAiLCJhenAiOiJkYjMzOTllNy0wNzIxLTQ0ODktYjg2Ny1jNDRmYzdiYzQyNzIifQ.F-o-kNESluUz3Ta6ftEwy-tNUWPOwY-aHG43RNcVHP4HjHNas5uxvpA2Aw7YJTDrJ2amFSD9Ff74X-rroPXk7w
        explode: false
        in: header
        name: Authorization
        required: false
        schema:
          type: string
        style: simple
      responses:
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Unauthorized
        "403":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Forbidden
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Internal Server Error
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Not Found
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseAuthorizeResponseViewModel'
          description: OK
      security:
      - nebulasuite: []
      summary: Authorize an trusted app
      tags:
      - Authentication
      x-accepts:
      - '*/*'
  /trusted/apps:
    get:
      operationId: getTrustedApps
      parameters:
      - explode: true
        in: query
        name: page
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: size
        required: false
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Unauthorized
        "403":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Forbidden
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Internal Server Error
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponse'
          description: Not Found
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseListTrustedAppViewModel'
          description: OK
      security:
      - nebulasuite: []
      summary: Get list of trusted apps created in the system
      tags:
      - Manage trusted app
      x-accepts:
      - '*/*'
components:
  schemas:
    NebulaPagination:
      description: Pagination information for listing operations
      example:
        totalPages: 5
        totalElements: 10
      properties:
        totalElements:
          description: Total number of items of the operation carried out
          example: 10
          format: int32
          type: integer
        totalPages:
          description: Total number of available pages of the operation carried out
          example: 5
          format: int32
          type: integer
      required:
      - totalElements
      - totalPages
      type: object
    NebulaResponse:
      example:
        code: code
        pagination:
          totalPages: 5
          totalElements: 10
        message: message
        content: "{}"
      properties:
        content:
          type: object
        code:
          description: Execution response code
          type: string
        message:
          description: Message describing the status resulting from execution
          type: string
        pagination:
          $ref: '#/components/schemas/NebulaPagination'
      required:
      - code
      - message
      type: object
    CreateTrustedAppViewModel:
      example:
        name: name
        description: description
      properties:
        name:
          description: Trusted app name
          maxLength: 255
          minLength: 1
          pattern: (?i)^(?:(?!</?\w+(( |\t|/)+.*)?>).)*$
          type: string
        description:
          description: Trusted app description
          maxLength: 1024
          minLength: 0
          pattern: (?i)^(?:(?!</?\w+(( |\t|/)+.*)?>).)*$
          type: string
      required:
      - name
      type: object
    DetailedTrustedAppViewModel:
      example:
        permissions:
        - permissions
        - permissions
        appId: appId
        tenantId: tenantId
        name: name
        description: description
        groups:
        - groups
        - groups
        expiration: 0
        status: ENABLED
        jwtSignatureAlgorithm: HMAC_SHA256
      properties:
        appId:
          description: UUID of the trusted app
          type: string
        tenantId:
          description: Tenant ID
          type: string
        name:
          description: Name defined in the trusted app
          type: string
        status:
          description: Current status of the trusted app
          enum:
          - ENABLED
          - DISABLED
          type: string
        permissions:
          description: List of permissions assigned to the trusted app
          items:
            description: Permission granted to the trusted app
            type: string
          type: array
        description:
          description: Description defined in the trusted app
          type: string
        groups:
          description: List of groups defined in the trusted app
          items:
            description: Group (GID) defined in the trusted app
            type: string
          type: array
        jwtSignatureAlgorithm:
          description: Algorithm defined to generate the token to perform the authorisation
          enum:
          - HMAC_SHA256
          - HMAC_SHA384
          - HMAC_SHA512
          type: string
        expiration:
          description: Expiration time (in seconds) defined for the token generated
            when the trusted app is authorised
          format: int32
          type: integer
      required:
      - appId
      - description
      - expiration
      - groups
      - jwtSignatureAlgorithm
      - name
      - permissions
      - status
      - tenantId
      type: object
    NebulaResponseDetailedTrustedAppViewModel:
      example:
        code: code
        pagination:
          totalPages: 5
          totalElements: 10
        message: message
        content:
          permissions:
          - permissions
          - permissions
          appId: appId
          tenantId: tenantId
          name: name
          description: description
          groups:
          - groups
          - groups
          expiration: 0
          status: ENABLED
          jwtSignatureAlgorithm: HMAC_SHA256
      properties:
        content:
          $ref: '#/components/schemas/DetailedTrustedAppViewModel'
        code:
          description: Execution response code
          type: string
        message:
          description: Message describing the status resulting from execution
          type: string
        pagination:
          $ref: '#/components/schemas/NebulaPagination'
      required:
      - code
      - message
      type: object
    TrustedAppSecParamsViewModel:
      example:
        tokenExpiration: 60
        signatureAlgorithm: HMAC_SHA256
        status: ENABLED
      properties:
        tokenExpiration:
          description: Expiration time (in minutes) of the token to be generated by
            the system when the trusted app is authorised
          example: 60
          format: int32
          maximum: 1440
          minimum: 1
          type: integer
        signatureAlgorithm:
          description: Algorithm used by the trusted app to generate the token to
            perform the authorisation
          enum:
          - HMAC_SHA256
          - HMAC_SHA384
          - HMAC_SHA512
          - HMAC_SHA256
          - HMAC_SHA384
          - HMAC_SHA512
          type: string
        status:
          description: Trusted app status
          enum:
          - ENABLED
          - DISABLED
          - ENABLED
          - DISABLED
          type: string
      required:
      - signatureAlgorithm
      - status
      - tokenExpiration
      type: object
    PermissionsBody:
      example:
        permissions:
        - DISABLE_AUTH_FIRST
        - DISABLE_AUTH_FIRST
      properties:
        permissions:
          description: List of permissions granted to the trusted app
          items:
            description: Permission granted to the trusted app
            enum:
            - DISABLE_AUTH_FIRST
            - DISABLE_AUTH_SECOND
            - DISABLE_PIN_POLICY
            type: string
          type: array
      required:
      - permissions
      type: object
    AccessGroupsViewModel:
      example:
        groups:
        - groups
        - groups
      properties:
        groups:
          description: List of GUIDs to be assigned to the trusted app
          items:
            description: GUID to be assigned to the trusted app
            type: string
          type: array
      required:
      - groups
      type: object
    NebulaResponseRegenerateTrustedAppViewModel:
      example:
        code: code
        pagination:
          totalPages: 5
          totalElements: 10
        message: message
        content:
          accessKey: 6160123E656BE6DFF4CBec3174c541CAe8feccb63f9D3107d36e1841BAd8ddd3
          name: Trusted App demo
      properties:
        content:
          $ref: '#/components/schemas/RegenerateTrustedAppViewModel'
        code:
          description: Execution response code
          type: string
        message:
          description: Message describing the status resulting from execution
          type: string
        pagination:
          $ref: '#/components/schemas/NebulaPagination'
      required:
      - code
      - message
      type: object
    RegenerateTrustedAppViewModel:
      example:
        accessKey: 6160123E656BE6DFF4CBec3174c541CAe8feccb63f9D3107d36e1841BAd8ddd3
        name: Trusted App demo
      properties:
        name:
          description: Trusted app name
          example: Trusted App demo
          type: string
        accessKey:
          description: Trusted app access key
          example: 6160123E656BE6DFF4CBec3174c541CAe8feccb63f9D3107d36e1841BAd8ddd3
          type: string
      type: object
    LoginResponseViewModel:
      example:
        token: JWT
      properties:
        token:
          example: JWT
          type: string
      required:
      - token
      type: object
    NebulaResponseLoginResponseViewModel:
      example:
        code: code
        pagination:
          totalPages: 5
          totalElements: 10
        message: message
        content:
          token: JWT
      properties:
        content:
          $ref: '#/components/schemas/LoginResponseViewModel'
        code:
          description: Execution response code
          type: string
        message:
          description: Message describing the status resulting from execution
          type: string
        pagination:
          $ref: '#/components/schemas/NebulaPagination'
      required:
      - code
      - message
      type: object
    AuthorizeResponseViewModel:
      example:
        authorization: JWT
        grants:
        - DISABLE_AUTH_FIRST
        - DISABLE_AUTH_FIRST
        expiration: 10
      properties:
        authorization:
          description: Token generated for future operations in nebulaSUITE
          example: JWT
          type: string
        expiration:
          description: Token expiration time in minutes
          example: 10
          format: int64
          type: integer
        grants:
          description: Permissions held with the generated token
          items:
            description: Permissions held with the generated token
            enum:
            - DISABLE_AUTH_FIRST
            - DISABLE_AUTH_SECOND
            - DISABLE_PIN_POLICY
            type: string
          type: array
      required:
      - authorization
      - expiration
      - grants
      type: object
    NebulaResponseAuthorizeResponseViewModel:
      example:
        code: code
        pagination:
          totalPages: 5
          totalElements: 10
        message: message
        content:
          authorization: JWT
          grants:
          - DISABLE_AUTH_FIRST
          - DISABLE_AUTH_FIRST
          expiration: 10
      properties:
        content:
          $ref: '#/components/schemas/AuthorizeResponseViewModel'
        code:
          description: Execution response code
          type: string
        message:
          description: Message describing the status resulting from execution
          type: string
        pagination:
          $ref: '#/components/schemas/NebulaPagination'
      required:
      - code
      - message
      type: object
    NebulaResponseListTrustedAppViewModel:
      example:
        code: code
        pagination:
          totalPages: 5
          totalElements: 10
        message: message
        content:
        - permissions:
          - permissions
          - permissions
          appId: appId
          tenantId: tenantId
          name: name
          status: ENABLED
        - permissions:
          - permissions
          - permissions
          appId: appId
          tenantId: tenantId
          name: name
          status: ENABLED
      properties:
        content:
          items:
            $ref: '#/components/schemas/TrustedAppViewModel'
          type: array
        code:
          description: Execution response code
          type: string
        message:
          description: Message describing the status resulting from execution
          type: string
        pagination:
          $ref: '#/components/schemas/NebulaPagination'
      required:
      - code
      - message
      type: object
    TrustedAppViewModel:
      example:
        permissions:
        - permissions
        - permissions
        appId: appId
        tenantId: tenantId
        name: name
        status: ENABLED
      properties:
        appId:
          description: UUID of the trusted app
          type: string
        tenantId:
          description: Tenant ID
          type: string
        name:
          description: Name defined in the trusted app
          type: string
        status:
          description: Current status of the trusted app
          enum:
          - ENABLED
          - DISABLED
          type: string
        permissions:
          description: List of permissions assigned to the trusted app
          items:
            description: Permission granted to the trusted app
            type: string
          type: array
      required:
      - appId
      - name
      - permissions
      - status
      - tenantId
      type: object
    GroupViewModel:
      example:
        gid: Group demo
        guid: 4bd1acc4-6827-3543-813c-3983297479f0
      properties:
        gid:
          description: "Name of the group. In case the group does not exist in nebulaUSERS,\
            \ it shall have the value of GUID"
          example: Group demo
          type: string
        guid:
          description: UUID of the group
          example: 4bd1acc4-6827-3543-813c-3983297479f0
          type: string
      required:
      - gid
      - guid
      type: object
    NebulaResponseListGroupViewModel:
      example:
        code: code
        pagination:
          totalPages: 5
          totalElements: 10
        message: message
        content:
        - gid: Group demo
          guid: 4bd1acc4-6827-3543-813c-3983297479f0
        - gid: Group demo
          guid: 4bd1acc4-6827-3543-813c-3983297479f0
      properties:
        content:
          items:
            $ref: '#/components/schemas/GroupViewModel'
          type: array
        code:
          description: Execution response code
          type: string
        message:
          description: Message describing the status resulting from execution
          type: string
        pagination:
          $ref: '#/components/schemas/NebulaPagination'
      required:
      - code
      - message
      type: object
  securitySchemes:
    Authorization:
      bearerFormat: JWT
      scheme: bearer
      type: http
    nebulasuite:
      bearerFormat: JWT
      scheme: bearer
      type: http

