openapi: 3.0.1
info:
  title: Authentication API
  version: v4
externalDocs:
  description: API Documentation
  url: https://portal.nebulaservice.net/docs/developer/en/HTML/authentication.html
servers:
- url: https://api-ansmt01.nebulaservice.net
paths:
  /signin/auth/login/second:
    post:
      description: Second factor authentication
      operationId: authSecond
      parameters:
      - description: Token generated by the authorization previous step
        example: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3Mjg1OTQ1OTcsImp0aSI6ImRiNzc3YWM3LTllNmMtNDk0OS1hY2RlLWZhOThiYTNlNjc2MyIsImx2bCI6InNpbXBsZSIsInVpZCI6Im93bmVyIiwidXVpZCI6IjAxZDNlMWZjLTk0ZDktMzRkZC04ZWRjLTUxN2UzMzZhMDYwNiIsInR1aWQiOiJkZWM0MjEwZS1jYzg4LTNkZmUtOTI3NC0wNDE3MWM2NmM4MmQiLCJyb2xlcyI6eyJuZWJ1bGF1c2VycyI6ImJhc2ljIiwibmVidWxhY2VydCI6IkNlcnRPd25lciIsIm5lYnVsYXNpZ24tb2xkIjoib3duZXIiLCJuZWJ1bGFzaWduIjoib3duZXIifSwiYXV0aE9yaWdpbiI6ImNsb3VkIiwiZW1haWwiOiJzYW5kcmEucm9kcmlndWV6QHZpbnRlZ3Jpcy5jb20iLCJtYXhleHAiOjE3Mjg1OTQ1ODQ3NzZ9.DPCuqkV-Eipzo7cxVSCFveME4LJgdERpowcekHJOIfk
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionAndChallengeViewModel'
        required: true
      responses:
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Not Found
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Internal Server Error
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NebulaResponseResponseCodeTokenWithLevelViewModel'
          description: OK
      summary: Second factor authentication
      tags:
      - Authentication
      x-content-type: application/json
      x-accepts:
      - '*/*'
      - application/json
  /signin/auth/login/first:
    post:
      description: First factor authentication
      operationId: authFirst
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthViewModel'
        required: true
      responses:
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Not Found
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Internal Server Error
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NebulaResponseResponseCodeTokenWithLevelViewModel'
          description: OK
      summary: First factor authentication
      tags:
      - Authentication
      x-content-type: application/json
      x-accepts:
      - '*/*'
      - application/json
  /signin/auth/login/challenge/{authenticator}:
    get:
      description: Get challenge
      operationId: getChallenge
      parameters:
      - explode: false
        in: path
        name: authenticator
        required: true
        schema:
          type: string
        style: simple
      - description: Token generated by the authorization previous step
        example: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3Mjg1OTQ1OTcsImp0aSI6ImRiNzc3YWM3LTllNmMtNDk0OS1hY2RlLWZhOThiYTNlNjc2MyIsImx2bCI6InNpbXBsZSIsInVpZCI6Im93bmVyIiwidXVpZCI6IjAxZDNlMWZjLTk0ZDktMzRkZC04ZWRjLTUxN2UzMzZhMDYwNiIsInR1aWQiOiJkZWM0MjEwZS1jYzg4LTNkZmUtOTI3NC0wNDE3MWM2NmM4MmQiLCJyb2xlcyI6eyJuZWJ1bGF1c2VycyI6ImJhc2ljIiwibmVidWxhY2VydCI6IkNlcnRPd25lciIsIm5lYnVsYXNpZ24tb2xkIjoib3duZXIiLCJuZWJ1bGFzaWduIjoib3duZXIifSwiYXV0aE9yaWdpbiI6ImNsb3VkIiwiZW1haWwiOiJzYW5kcmEucm9kcmlndWV6QHZpbnRlZ3Jpcy5jb20iLCJtYXhleHAiOjE3Mjg1OTQ1ODQ3NzZ9.DPCuqkV-Eipzo7cxVSCFveME4LJgdERpowcekHJOIfk
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      responses:
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Not Found
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Internal Server Error
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NebulaResponseResponseCodeTokenWithChallengeVierModel'
          description: OK
      summary: Get challenge
      tags:
      - Authentication
      x-accepts:
      - '*/*'
      - application/json
  /signin/auth/login/authenticators:
    get:
      description: Get authenticators
      operationId: getAuthenticators
      parameters:
      - description: Token generated by the authorization previous step
        example: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3Mjg1OTQ1OTcsImp0aSI6ImRiNzc3YWM3LTllNmMtNDk0OS1hY2RlLWZhOThiYTNlNjc2MyIsImx2bCI6InNpbXBsZSIsInVpZCI6Im93bmVyIiwidXVpZCI6IjAxZDNlMWZjLTk0ZDktMzRkZC04ZWRjLTUxN2UzMzZhMDYwNiIsInR1aWQiOiJkZWM0MjEwZS1jYzg4LTNkZmUtOTI3NC0wNDE3MWM2NmM4MmQiLCJyb2xlcyI6eyJuZWJ1bGF1c2VycyI6ImJhc2ljIiwibmVidWxhY2VydCI6IkNlcnRPd25lciIsIm5lYnVsYXNpZ24tb2xkIjoib3duZXIiLCJuZWJ1bGFzaWduIjoib3duZXIifSwiYXV0aE9yaWdpbiI6ImNsb3VkIiwiZW1haWwiOiJzYW5kcmEucm9kcmlndWV6QHZpbnRlZ3Jpcy5jb20iLCJtYXhleHAiOjE3Mjg1OTQ1ODQ3NzZ9.DPCuqkV-Eipzo7cxVSCFveME4LJgdERpowcekHJOIfk
        explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      responses:
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Not Found
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Bad Request
        "500":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Internal Server Error
        "401":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NebulaResponseStringVoid'
          description: Unauthorized
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NebulaResponseResponseCodeTokenWithAuthenticatorsViewModel'
          description: OK
      summary: Get authenticators
      tags:
      - Authentication
      x-accepts:
      - '*/*'
      - application/json
components:
  schemas:
    NebulaResponseStringVoid:
      example:
        code: code
        message: message
        content: "{}"
      properties:
        code:
          type: string
        message:
          type: string
        content:
          type: object
      type: object
    SessionAndChallengeViewModel:
      example:
        session: session
        challenge: challenge
      properties:
        session:
          description: The authentication session
          type: string
        challenge:
          description: The solved challenge
          type: string
      required:
      - challenge
      - session
      type: object
    NebulaResponseResponseCodeTokenWithLevelViewModel:
      example:
        code: OK
        message: message
        content:
          lvl: lvl
          token: JWT
      properties:
        code:
          enum:
          - OK
          - INVALID_REQUEST
          - SERVER_ERROR
          - RESOURCE_NOT_FOUND
          - BAD_PARAMS
          - UNAUTHORIZED_CLIENT
          - INVALID_TOKEN
          type: string
        message:
          type: string
        content:
          $ref: '#/components/schemas/TokenWithLevelViewModel'
      type: object
    TokenWithLevelViewModel:
      example:
        lvl: lvl
        token: JWT
      properties:
        token:
          description: JWT Token
          example: JWT
          type: string
        lvl:
          description: level
          type: string
      required:
      - lvl
      - token
      type: object
    AuthViewModel:
      example:
        password: password
        tuid: tuid
        url: url
        username: username
      properties:
        username:
          description: The user identifier
          type: string
        password:
          description: The user password
          type: string
        tuid:
          description: The client identifier (not necessary if url is set)
          type: string
        url:
          description: The url (not necessary if client identifier is set)
          type: string
      required:
      - password
      - username
      type: object
    NebulaResponseResponseCodeTokenWithChallengeVierModel:
      example:
        code: OK
        message: message
        content:
          lvl: string
          session: string
          challenge: string
          token: JWT
      properties:
        code:
          enum:
          - OK
          - INVALID_REQUEST
          - SERVER_ERROR
          - RESOURCE_NOT_FOUND
          - BAD_PARAMS
          - UNAUTHORIZED_CLIENT
          - INVALID_TOKEN
          type: string
        message:
          type: string
        content:
          $ref: '#/components/schemas/TokenWithChallengeVierModel'
      type: object
    TokenWithChallengeVierModel:
      example:
        lvl: string
        session: string
        challenge: string
        token: JWT
      properties:
        token:
          description: Authentication token (Authorization header must contain this
            value on next operations)
          example: JWT
          type: string
        lvl:
          description: "The authentication level. One of [simple, authentication,\
            \ robust]"
          example: string
          type: string
        challenge:
          description: The authentication challenge
          example: string
          type: string
        session:
          description: The authentication session
          example: string
          type: string
      type: object
    NebulaResponseResponseCodeTokenWithAuthenticatorsViewModel:
      example:
        code: OK
        message: message
        content:
          authenticators: "[string, string]"
          token: JWT
      properties:
        code:
          enum:
          - OK
          - INVALID_REQUEST
          - SERVER_ERROR
          - RESOURCE_NOT_FOUND
          - BAD_PARAMS
          - UNAUTHORIZED_CLIENT
          - INVALID_TOKEN
          type: string
        message:
          type: string
        content:
          $ref: '#/components/schemas/TokenWithAuthenticatorsViewModel'
      type: object
    TokenWithAuthenticatorsViewModel:
      example:
        authenticators: "[string, string]"
        token: JWT
      properties:
        token:
          description: Authentication token (Authorization header must contain this
            value on next operations)
          example: JWT
          type: string
        authenticators:
          description: List containing the available authenticators
          example: "[string, string]"
          items:
            description: List containing the available authenticators
            example: "[string, string]"
            type: string
          type: array
      type: object
  securitySchemes:
    Authorization:
      bearerFormat: JWT
      scheme: bearer
      type: http

